# reusable workflow triggered by other actions
name: Continuous Integration

on:
  workflow_call:
    secrets:
      charmcraft-credentials:
        required: true

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.2.2
        with:
          credentials: "${{ secrets.charmcraft-credentials }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install tox
      - run: tox -e unit
