name: Update Charm Libraries on dispatch from a Shared Workflow

on:
  workflow_dispatch:
    inputs:
      charmcraft_channel:
        description: Channel from which to install charmcraft
        default: 'latest/candidate'
        required: false
        type: string

jobs:
  bump-libraries:
    name: Check Charm Library Versions Using a Shared Workflow
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/update-libs.yaml@v0.0.1
    with:
      charmcraft_channel: 'latest/candidate'
    secrets:
      CHARMCRAFT_CREDENTIALS: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"
      PAT: "${{ secrets.PAT }}"
