name: Update Charm Libraries on Schedule from a Shared Workflow

on: 
  schedule:
    # Every day at 15:50PM UTC
    - cron: '50 15 * * *'

jobs:
  bump-libraries:
    name: Check Charm Library Versions Using a Shared Workflow
    uses: ca-scribner/test-multi-charm/.github/workflows/update-libs.yaml@v0.0.1
    with:
      charmcraft_channel: 'latest/candidate'
    secrets:
      CHARMCRAFT_CREDENTIALS: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"
      PAT: "${{ secrets.PAT }}"
