name: Execute Renovate on a Schedule

on:
  schedule:
    # Every day at 1:00AM UTC
    - cron: '0 1 * * *'

jobs:
  renovate-repo:
    name: Run Renovate
    uses: ./.github/workflows/renovate.yaml
    with:
      charmcraft_channel: 'latest/candidate'
    secrets:
      RENOVATE_TOKEN: "${{ secrets.RENOVATE_TOKEN }}"
