# reusable workflow triggered by other actions
name: Test using global variable for RUNS_ON

on:
  pull_request:
  push:

env:
  RUNS_ON: ubuntu-20.04

jobs:
  test-job:
    name: Check libraries
    runs-on: ${{ env.RUNS_ON }}
    steps:
      - name: echo from context
        run: "echo from context: ${{ env.RUNS_ON }}"
      - name: echo from env
        run: "echo from env: $RUNS_ON"
